//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("This .NET assembly is part of DavidLievrouw.Utils.")]
[assembly: System.Reflection.AssemblyCopyright("Created by David Lievrouw in 2016, License: MIT")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyCompany("David Lievrouw")]
[assembly: System.Reflection.AssemblyProduct("DavidLievrouw.Utils")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyDelaySign(false)]


